- block:
  - name: Place anyenv repository
    git:
      repo: https://github.com/riywo/anyenv.git
      dest: "{{ ansible_env.HOME }}/.anyenv"
      version: master

  - name: Add init script of anyenv to .bashrc
    blockinfile:
      dest: "{{ ansible_env.HOME }}/.bashrc"
      block: |
        if [ -e "~/.anyenv" ]; then
          export PATH=$HOME/.anyenv/bin:$PATH
          eval "$(anyenv init -)"
        fi
      marker: "# {mark} : Insert by Ansible in order to load pyenv"
  tags: anyenv_install

